#数据库配置
spring:
  datasource:
    url: jdbc:mysql://39.97.179.164:3306/nice_bbs?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: nice
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      jdbc-url: jdbc:mysql://39.97.179.164:3306/nice_bbs?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: nice
#      idle-timeout: 0
      minimum-idle: 0
      max-lifetime: 0
    #      driver-class-name: com.alibaba.druid.proxy.DruidDriver
    type: com.zaxxer.hikari.HikariDataSource


  #解决bean重复定义
  main:
    allow-bean-definition-overriding: true
  #redis配置
  redis:
    host: 39.97.179.164
    port: 6380


  quartz:
    properties:
      org:
        quartz:
            dataSource:
              quartzDS:
                driver: com.mysql.jdbc.Driver
                URL: jdbc:mysql://39.97.179.164:3306/nice_bbs?useUnicode=true&characterEncoding=UTF-8&useSSL=false
                user: root
                password: nice
                maxConnection: 10
                validationQuery: select bbs_user_id from bbs_user limit 0,1;
                validateOnCheckout: true
                idleConnectionValidationSeconds: 50
                maxCachedStatementsPerConnection: 120
                discardIdleConnectionsSeconds: 0
                connectionProvider:
                  class: com.nice.config.quartz.QuartzConnectionProvider
            scheduler:
              instanceName: clusteredScheduler
              instanceId: AUTO
            jobStore:
              class: org.quartz.impl.jdbcjobstore.JobStoreTX
              driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
              tablePrefix: QRTZ_
              isClustered: true
              clusterCheckinInterval: 10000
              useProperties: false
              dataSource: quartzDS
            threadPool:
              class: org.quartz.simpl.SimpleThreadPool
              threadCount: 10
              threadPriority: 5
              threadsInheritContextClassLoaderOfInitializingThread: true
        #数据库方式
        job-store-type: jdbc
  #thymeleaf配置
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
    encoding: UTF-8




#mybatis配置
mybatis:
  configuration:
    #驼峰命名
    map-underscore-to-camel-case: true
  #mapper路径
  mapper-locations: classpath:com/nice/mapper/*.xml
  #实体类包名
  type-aliases-package: com.nice.domain


logging:
  config: classpath:log4j2.xml
#  level: info