#数据库配置
spring:
  datasource:
    url: jdbc:mysql://39.97.179.164:3306/nice_bbs?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: nice
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      jdbc-url: jdbc:mysql://39.97.179.164:3306/nice_bbs?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: nice
#      idle-timeout: 0
      minimum-idle: 0
      max-lifetime: 0
    #      driver-class-name: com.alibaba.druid.proxy.DruidDriver
    type: com.zaxxer.hikari.HikariDataSource

  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
    encoding: UTF-8




#mybatis配置
mybatis:
  configuration:
    #驼峰命名
    map-underscore-to-camel-case: true
  #mapper路径
  mapper-locations: classpath:com/nice/mapper/*.xml
  #实体类包名
  type-aliases-package: com.nice.domain